add Morgane post linkedin
osrd-project/osrd-website pull request #112
Opened 2023-05-22 07:49 UTC by cassandrafestoc

2023-05-23 09:34 UTC, cassandrafestoc commented
Hello ! 

Voici un nouvel article pour le blog : le post LinkedIn de Morgane !

2023-05-24 08:46 UTC, axrolld requested changes

2023-05-24 08:46 UTC, axrolld commented on content/blog/news/morganepostlinkedin.fr.md
> +Il s’agit de la réservation d’espace/temps sur le réseau, par les entreprises ferroviaires (EF), comme SNCF Voyageurs. Ces réservations se font des années en amont (A-3). Les EF peuvent également fai
```suggestion
Il s’agit de la réservation d’espace/temps sur le réseau, par les entreprises ferroviaires (EF), comme SNCF Voyageurs. Ces réservations se font généralement des années en amont (A-3). Les EF peuvent également faire des demandes de sillons en urgence (appelés sillons de dernière minute), de A-1 jusqu’au jour J.
```

2023-05-24 08:46 UTC, axrolld commented on content/blog/news/morganepostlinkedin.fr.md
> +Le logiciel OSRD, en plus de disposer d’un simulateur ferroviaire pour la planification des horaires, va également permettre de traiter les demandes de sillon de dernière minute de façon automatisée
`en quelques secondes (tout au plus 3min)` is quite weird, we are promising a computing time that varies from 2 orders of magnitude.

2023-05-30 19:36 UTC, ttsirkia commented
The picture is huge (over 15 MB) and should be optimized for web.

2023-06-07 14:45 UTC, flomonster requested changes

2023-06-07 14:45 UTC, flomonster commented on content/blog/news/morganepostlinkedin.fr.md
Can you move this in `osrd-website/content/blog/news/2023/post_linkedin_morgane`

2023-06-07 14:45 UTC, flomonster commented on content/blog/news/pictures/morganepostlinkedin.png
We could convert this picture as `.webp`.

2023-06-14 13:58 UTC, axrolld approved these changes

2023-06-14 13:58 UTC, merged