add article i&a5
osrd-project/osrd-website pull request #117
Opened 2023-06-09 13:42 UTC by cassandrafestoc

2023-06-09 13:58 UTC, loic-hamelin approved these changes
Très bien merci :)

2023-06-09 14:16 UTC, axrolld requested changes
Juste un mini changement sur une majuscule qui n'est pas nécessaire selon moi

2023-06-09 14:16 UTC, axrolld commented on content/blog/news/_index.fr.md
> +Le lendemain, Nathanaël Dias, Chargé d’étude exploitation ferroviaire, nous a présenté son métier, et le processus d’élaboration d’une Etude exploitation. Il a insisté sur l’importance de partager le
```suggestion
Le lendemain, Nathanaël Dias, Chargé d’étude exploitation ferroviaire, nous a présenté son métier, et le processus d’élaboration d’une étude exploitation. Il a insisté sur l’importance de partager les résultats et les travaux. 
```
Pourquoi un E majuscule ici ?

2023-06-13 07:57 UTC, flomonster approved these changes

2023-06-14 06:09 UTC, axrolld approved these changes

2023-06-14 14:00 UTC, merged