Màj financeurs
osrd-project/osrd-website pull request #128
Opened 2023-08-11 07:22 UTC by loic-hamelin

Il manquait Réseau et l'Etat

2023-08-11 07:56 UTC, axrolld requested changes
Need to update the english file as well, otherwise i approve the changes :D

2023-10-03 14:31 UTC, flomonster approved these changes

2023-10-03 14:47 UTC, multun commented on content/about/governance/index.en.md
> +- A team of full-time developpers at SNCF Réseau, financed by SNCF Réseau, the French government and the European Union
```suggestion
- A team of full-time developpers at SNCF Réseau, financed by SNCF Réseau, the French state and the European Union
```

2023-10-04 08:23 UTC, multun approved these changes

2023-10-04 09:18 UTC, axrolld approved these changes

2023-10-06 12:09 UTC, merged