SCSS : some rules & usage of cx()
osrd-project/osrd-website pull request #139
Opened 2023-10-10 09:34 UTC by nicolaswurtz

2023-10-10 12:05 UTC, anisometropie commented on content/docs/guides/contribute/conventions/front.en.md
> +Les classes sont **séparées** chacune dans un `string` et les opérations booléennes ou autres sont réalisées dans un objet qui retournera — ou pas — le nom de propriété comme nom de classe à utiliser
```suggestion
Les classes sont **séparées** chacune dans un `string` et les opérations booléennes ou autres sont réalisées dans un objet qui retournera — ou pas — le nom de propriété comme nom de classe à utiliser dans le CSS.
```

2023-10-10 12:13 UTC, anisometropie requested changes

2023-10-10 12:13 UTC, anisometropie commented on content/docs/guides/contribute/conventions/front.en.md
> +Cependant, quand cela est nécessaire — tests pour l'utilisation d'une classe, concaténation, etc. — nous utilisons la librairie [classnames](https://github.com/JedWatson/classnames) qui préconise l'u
```suggestion
Cependant, quand cela est nécessaire —&nbsp;tests pour l'utilisation d'une classe, concaténation, etc.&nbsp;— nous utilisons la librairie [classnames](https://github.com/JedWatson/classnames) qui préconise l'usage suivant :
```

2023-10-10 12:13 UTC, anisometropie commented on content/docs/guides/contribute/conventions/front.en.md
> +Les classes sont **séparées** chacune dans un `string` et les opérations booléennes ou autres sont réalisées dans un objet qui retournera — ou pas — le nom de propriété comme nom de classe à utiliser
espace insécable pour les tirets d’incise

```suggestion
Les classes sont **séparées** chacune dans un `string` et les opérations booléennes ou autres sont réalisées dans un objet qui retournera —&nbsp;ou pas&nbsp;— le nom de propriété comme nom de classe à utiliser dans le CSS.
```

2023-11-22 18:14 UTC, nicolaswurtz commented on content/docs/guides/contribute/conventions/front.en.md
> +Cependant, quand cela est nécessaire — tests pour l'utilisation d'une classe, concaténation, etc. — nous utilisons la librairie [classnames](https://github.com/JedWatson/classnames) qui préconise l'u
Changed, thx !

2023-11-22 18:14 UTC, nicolaswurtz commented on content/docs/guides/contribute/conventions/front.en.md
> +Les classes sont **séparées** chacune dans un `string` et les opérations booléennes ou autres sont réalisées dans un objet qui retournera — ou pas — le nom de propriété comme nom de classe à utiliser
Changed, thx !

2023-11-27 18:03 UTC, anisometropie approved these changes

2023-11-30 17:51 UTC, merged