rewrite switch section
osrd-project/osrd-website pull request #141
Opened 2023-10-12 20:00 UTC by younesschrifi

Close #133

2023-11-10 17:26 UTC, Tguisnet requested changes
Good work thanks ! I request few changes.

2023-11-10 17:26 UTC, Tguisnet commented on content/docs/explanation/models/data-models-full-example/index.en.md
> +**1) Switches**
We should remove distinction between links and switches

2023-11-10 17:26 UTC, Tguisnet commented on content/docs/explanation/models/data-models-full-example/index.en.md
> +Whether for switches or track section links, links and groups are not part of the switch itself, but of a `Node` object, which is shared by switches in the same model.
```suggestion
Whether for switches or track section links, links and groups are not part of the switch itself, but of a `NodeType` object, which is shared by switches in the same model.
```

2023-11-10 17:26 UTC, Tguisnet commented on content/docs/explanation/models/data-models-full-example/index.en.md
>  * `groups`: A mapping from group names to lists of links between two ports.
I should add a better explanation of those terms, maybe including the word `branch`

2023-11-10 17:26 UTC, Tguisnet commented on content/docs/explanation/models/data-models-full-example/index.en.md
>  **2) The Cross Switch**
```suggestion
**2) The Crossing**
```

2023-11-10 17:26 UTC, Tguisnet commented on content/docs/explanation/models/data-models-full-example/index.en.md
>  **3) The Double cross switch**
```suggestion
**3) The Double slip switch**
```

2023-11-10 17:26 UTC, Tguisnet commented on content/docs/explanation/models/data-models-full-example/index.fr.md
> +Il est important de noter que ces noeuds sont présents en dur dans le code du projet. Seul les `extended_switch_type` ajoutés par l'utilisateur apparaîtront dans le railjson.
I'll turn *en dur* by *par défaut* 
This part is not present in the English translation.

2023-11-10 17:26 UTC, Tguisnet commented on content/docs/explanation/models/data-models-full-example/index.fr.md
> +![Diagramme des positions de l'aiguillage de croisement simple](svg_diagrams/SingleSlipCrossing_A2toB2.svg)
This part is not present in the English translation.

2023-12-04 10:28 UTC, multun requested changes

2023-12-05 17:18 UTC, merged