Add documentation about updating dependencies in batch
osrd-project/osrd-website pull request #142
Opened 2023-10-27 12:47 UTC by Castavo

2023-10-27 12:56 UTC, flomonster requested changes
Thanks for the PR! A few things to fix though.

2023-10-27 12:56 UTC, flomonster commented on content/docs/guides/contribute/batch-updating-dependencies.en.md
> +3. Check that all [dependabot editoast PRs](https://github.com/osrd-project/osrd/lls?q=is%3Aopen+label%3Aarea%3Aeditoast+label%3Adependencies) are included in your update.
I get a 404 with this URL

2023-10-27 12:56 UTC, flomonster commented on content/docs/guides/contribute/batch-updating-dependencies.en.md
> +    * *If you're not*, you can go check the versions used by dependabot in [its PRs](https://github.com/osrd-project/osrd/lls?q=is%3Aopen+label%3Aarea%3Aeditoast+label%3Adependencies) and update the
I get a 404 with this URL

2023-10-27 12:56 UTC, flomonster commented on content/docs/guides/contribute/batch-updating-dependencies.en.md
> +    * *If you're using VSCode* you can install the `crates` extension and run the "update all dependencies" command.
```suggestion
    * *If you're using VSCode* you can install the `serayuzgur.crates` extension and run the "update all dependencies" command.  
```

2023-10-27 12:56 UTC, flomonster commented on content/docs/guides/contribute/batch-updating-dependencies.en.md
> +    * *If you're using VSCode* you can install the `crates` extension and run the "update all dependencies" command.
We could also include a ling to https://marketplace.visualstudio.com/items?itemName=serayuzgur.crates?

2023-10-27 13:20 UTC, hamz2a commented
LGTM

2023-11-02 09:14 UTC, flomonster approved these changes

2023-11-21 12:29 UTC, Tguisnet approved these changes

2023-11-21 12:30 UTC, merged