rtk-cache
osrd-project/osrd-website pull request #150
Opened 2023-11-14 12:48 UTC by anisometropie

2023-11-15 08:10 UTC, axrolld requested changes
Can't fact check the technical details here but i found a few typos 😇

2023-11-15 08:10 UTC, axrolld commented on content/docs/guides/contribute/conventions/front.fr.md
>  Par conséquent les appels au store en lecture et en écriture doivent être passés un niveau de la vue, en irrigant par des _props_ et _states_ les composants proposées par la vue.
Juste au dessus : `la vue passée en props` avec un e à passé, non ? C'est hors de ta PR donc je peux pas comment cette ligne spécifiquement

2023-11-15 08:10 UTC, axrolld commented on content/docs/guides/contribute/conventions/front.fr.md
> +##### souscriptions à la donnée
On veut pas une majuscule ici ?
```suggestion
##### Souscriptions à la donnée
```

2023-11-15 08:10 UTC, axrolld commented on content/docs/guides/contribute/conventions/front.fr.md
> +Dans la terminologie de RTK query, Lorsqu’un composant react appele un endpoint définit dans RTK Query, il _souscrit_ à la donnée.
```suggestion
Dans la terminologie de RTK query, Lorsqu’un composant react appelle un endpoint définit dans RTK Query, il _souscrit_ à la donnée.
```

2023-11-15 08:10 UTC, axrolld commented on content/docs/guides/contribute/conventions/front.fr.md
> +Dès que le dernier composant est démonté, la donnée est supprimé du cache au bout d’un certain temps, configurable.
```suggestion
Dès que le dernier composant est démonté, la donnée est supprimée du cache au bout d’un certain temps, configurable.
```

2023-11-15 08:29 UTC, anisometropie commented on content/docs/guides/contribute/conventions/front.fr.md
>  Par conséquent les appels au store en lecture et en écriture doivent être passés un niveau de la vue, en irrigant par des _props_ et _states_ les composants proposées par la vue.
à mon avis c’est plutôt « Tout ce qui est *selector* est géré par la **vue** EST passé en props aux composants et sous-composants. »

2023-11-20 10:09 UTC, anisometropie commented on content/docs/guides/contribute/conventions/front.fr.md
>  Par conséquent les appels au store en lecture et en écriture doivent être passés un niveau de la vue, en irrigant par des _props_ et _states_ les composants proposées par la vue.
@nicolaswurtz

2023-11-20 10:18 UTC, axrolld approved these changes
Just the first comment to be check with @nicolaswurtz , otherwise LGTM !

2023-11-22 17:10 UTC, nicolaswurtz requested changes

2023-11-22 17:10 UTC, nicolaswurtz commented on content/docs/guides/contribute/conventions/front.fr.md
>  Par conséquent les appels au store en lecture et en écriture doivent être passés un niveau de la vue, en irrigant par des _props_ et _states_ les composants proposées par la vue.
Ah c'est fait, merci !

2023-11-30 17:49 UTC, nicolaswurtz approved these changes

2023-11-30 17:49 UTC, merged