guides: deployment
osrd-project/osrd-website pull request #152
Opened 2023-11-24 09:05 UTC by ElysaSrc

This modification add guides that cover deployments

2023-12-04 15:03 UTC, multun approved these changes

2023-12-07 10:18 UTC, celine-sncf requested changes
corrected a few typos

2023-12-07 10:18 UTC, celine-sncf commented on content/docs/explanation/containers-architecture/_index.fr.md
> +## Standard deployment
```suggestion
## Déploiement standard
```

2023-12-07 10:18 UTC, celine-sncf commented on content/docs/explanation/containers-architecture/_index.fr.md
> +Le gateway n'est pas seulement un proxy inverse avec le bundle front-end inclus, il fournit également tous les mécanismes d'authentification : utilisant OIDC ou des jetons.
```suggestion
Le gateway n'est pas seulement un proxy inverse avec le bundle front-end inclus, il fournit également tous les mécanismes d'authentification : utilisant OIDC ou des tokens.
```

2023-12-07 10:18 UTC, celine-sncf commented on content/docs/guides/deploy/_index.en.md
> +It's also possible to deploy manually each service of OSRD manually on a system, but we will not cover this topic within this guide.
```suggestion
It is also possible to deploy each service of OSRD manually on a system, but we will not cover this topic within this guide.
```

2023-12-07 10:18 UTC, celine-sncf commented on content/docs/guides/deploy/docker-compose/_index.en.md
> +Each service is configured with health checks, volume mounts, and necessary environment variables.
```suggestion
Each service is configured with health checks, volume mounts and necessary environment variables.
```

2023-12-07 12:26 UTC, ElysaSrc commented on content/docs/guides/deploy/kubernetes/_index.fr.md
> +## Configuration de la Helm Chart (values)
Ici je laisse values car c'est le terme technique des helm charts :)

2023-12-07 13:40 UTC, celine-sncf approved these changes
thank you for the corrections :)

2023-12-07 14:22 UTC, multun approved these changes

2023-12-07 16:06 UTC, multun approved these changes

2023-12-07 16:06 UTC, merged