doc: add french "point remarquable"
osrd-project/osrd-website pull request #158
Opened 2023-12-11 13:23 UTC by bougue-pe

link it to operational point

2023-12-11 13:36 UTC, shenriotpro requested changes
Thanks, I noticed a few minor issues

2023-12-11 13:36 UTC, shenriotpro commented on content/docs/railway-wiki/glossary/_index.fr.md
> +- **VUTP** : Voie unique temporaire à caractère permanent
I can't seem to notice the change here, was there a missing newline or something?

2023-12-11 13:36 UTC, shenriotpro commented on content/docs/railway-wiki/glossary/_index.fr.md
> +- **PO** : Point opérationnel : collection de points représentant un lieu d'intérêt, voir [exemple](../../explanation/models/data-models-full-example/#points-opérationnels-operationalpoints
It looks like we're missing a parenthesis.

2023-12-11 13:36 UTC, shenriotpro commented on content/docs/explanation/models/data-models-full-example/index.fr.md
> +De la même manière  , un pont au-dessus des voies sera **un** OperationalPoint, mais il comportera **plusieurs** OperationPointParts, une à l'intersection de chaque voies.
nit: it looks like there is a whitespace before a comma

2023-12-11 13:36 UTC, shenriotpro commented on content/docs/explanation/models/data-models-full-example/index.fr.md
> +De la même manière  , un pont au-dessus des voies sera **un** OperationalPoint, mais il comportera **plusieurs** OperationPointParts, une à l'intersection de chaque voies.
I also believe "chaque voie" should be singular.

2023-12-11 16:22 UTC, bougue-pe commented
Thanks @shenriotpro for the review: update done, I was too sketchy in the train :pray:

2023-12-12 09:39 UTC, shenriotpro approved these changes

2023-12-12 09:41 UTC, axrolld approved these changes

2023-12-12 09:46 UTC, merged