Remove Docsy submodule, update conf to Hugo 0.121.2, cleaning
osrd-project/osrd-website pull request #169
Opened 2024-01-27 09:06 UTC by nicolaswurtz

2024-01-29 11:00 UTC, woshilapin approved these changes

2024-01-31 16:38 UTC, flomonster requested changes
We need small changes in the README.

2024-01-31 16:38 UTC, flomonster commented on README.md
The docker installation steps should be updated. It seems like we don't need to install theme dependencies anymore but only to run the container.

2024-02-01 14:21 UTC, flomonster approved these changes
LGTM

2024-02-01 14:22 UTC, merged