doc: move dependencies bump batching in general principles
osrd-project/osrd-website pull request #178
Opened 2024-02-28 09:19 UTC by bougue-pe

Details for editoast are moved close to the code, in `osrd/editoast/README.md`

2024-02-28 09:26 UTC, flomonster approved these changes

2024-02-29 08:46 UTC, multun requested changes

2024-02-29 08:46 UTC, multun commented on content/docs/guides/contribute/contribute-code/general-principles.en.md
>  - **Don't reinvent every wheel**: as a counter to the previous point, don't reinvent everything at all costs.
frenglish

2024-02-29 08:46 UTC, multun commented on content/docs/guides/contribute/contribute-code/general-principles.fr.md
>  - **Ne pas réinventer la roue** : en opposition au point précédent, ne réinventez pas tout à tout prix.
frenglish

2024-02-29 09:18 UTC, bougue-pe commented on content/docs/guides/contribute/contribute-code/general-principles.en.md
>  - **Don't reinvent every wheel**: as a counter to the previous point, don't reinvent everything at all costs.
Thanks ! Directly amended into https://github.com/osrd-project/osrd-website/pull/178/commits/6b9188e01c759e254bc6bb98d89414deca05c1df

2024-02-29 09:18 UTC, bougue-pe commented on content/docs/guides/contribute/contribute-code/general-principles.fr.md
>  - **Ne pas réinventer la roue** : en opposition au point précédent, ne réinventez pas tout à tout prix.
Amended into https://github.com/osrd-project/osrd-website/pull/178/commits/6b9188e01c759e254bc6bb98d89414deca05c1df

2024-02-29 15:08 UTC, multun approved these changes

2024-02-29 15:08 UTC, merged