about: add an acknowledgements page
osrd-project/osrd-website pull request #77
Opened 2023-01-31 23:01 UTC by multun

2023-02-01 13:42 UTC, loic-hamelin commented
We would like to thank : 
- European Union and French Ministry of transportation for founding the project,
- SNCF Réseau DGEX for hosting the early project OSRD since a long time,
- SNCF Research and Development department for paving the way for simulation with SISYFE,
- and all the past, present and future contributors

2023-02-01 14:02 UTC, celine-sncf commented
- Add https://github.com/luteberget link for Bjørnar Steinnes Luteberget

2023-02-01 15:31 UTC, multun commented
@loic-hamelin @celine-sncf I addressed your comments

2023-02-01 17:56 UTC, axrolld requested changes

2023-02-01 17:56 UTC, axrolld commented on content/about/acknowledgments.fr.md
> + - Nathanaël Dias, pour son avis d'expert et sa revue du fonctionnement de l'application
Il manque un certain nombre de gens dans ces remerciements...
- Beaucoup de chargés d'études, qu'on peut regroupper dans la même ligne que Nathanael :
ARACHTINGI Augustin, ROUSSEL Jean-Nicolas, SAMBRAS Théophile, THOMSEN Yvan, Valentin AXEL, et tous ceux avec qui @bgiuliana , @carolnvg , ou @El-Youssef ont pu travailler
- Cyril et Elfride
- Toute l'équipe OSRD (je sais pas si ça se fait), dont les anciens membres de l'équipe (genre les stagiaires qui sont partis)
- Emmanuel Guigon
- Marion POSTEC qui nous a filé un coup de main sur les données
- etc

La liste est en réalité maxi longue

2023-02-01 17:58 UTC, axrolld commented on content/about/acknowledgments.fr.md
> + - Nathanaël Dias, pour son avis d'expert et sa revue du fonctionnement de l'application
+ les gens d'ESMERALDA, de QUALESI etc

2023-02-01 17:59 UTC, axrolld commented on content/about/acknowledgments.fr.md
> + - Nathanaël Dias, pour son avis d'expert et sa revue du fonctionnement de l'application
En fait si on se lance dans la liste de gens ou de projets spécifiques on est pas rendus... Je pense que la version que propose Loic est plus simple, plus globale, on oublie personne et on vexe personne

2023-04-11 17:35 UTC, axrolld commented
What's the status of this page ? Does it really make sense to start thanking everyone who contributed to the project ?

2024-03-01 10:03 UTC, closed without merging