about: merge use case pages
osrd-project/osrd-website pull request #80
Opened 2023-02-02 17:11 UTC by multun

2023-02-03 07:59 UTC, axrolld requested changes

2023-02-03 07:59 UTC, axrolld commented on content/about/use-case/_index.en.md
> +statement of requirements.
I find this sentence a bit weird. Here's my suggestion :

```suggestion
Timetabling is about designing a transport service in order
to meet the transit needs.
```

2023-02-03 07:59 UTC, axrolld commented on content/about/use-case/_index.en.md
> + - a microscopic railway infrastructure database
I get the idea but it can be interpreted like the database is microscopic. Even though it doesn't really make sense the overall bulletpoint ends up rather weird in my opinion. What about something like this ?
```suggestion
 - a railway infrastructure database at microscopic scale
```

2023-02-03 07:59 UTC, axrolld commented on content/about/use-case/_index.en.md
> +They enable informed public infrastructure investment decisions.
```suggestion
Operation studies assess the ability of the infrastructure to meet the demand,
and help balancing infrastructure capacity with transportation needs.
They enable informed public infrastructure investment decisions.
```

2023-02-03 07:59 UTC, axrolld commented on content/about/use-case/_index.en.md
> + - a microscopic railway infrastructure database
If we decide to change the corresponding bulletpoint above don't forget to change it here as well.

2023-02-03 07:59 UTC, axrolld commented on content/about/use-case/_index.en.md
> + - train path allowances, including an allowance distribution which minimizes energy use
Isn't the entire signalling system & station management missing ?

2023-02-03 07:59 UTC, axrolld commented on content/about/use-case/_index.en.md
> + - avoid generating conflicts[^conflict] with already planned train paths,
```suggestion
 - avoid generating conflicts[^conflict] with planned trains,
```

2023-02-03 10:44 UTC, multun commented on content/about/use-case/_index.en.md
> + - train path allowances, including an allowance distribution which minimizes energy use
station interlocking is part of conflict detection, I added a line about signaling simulation

2023-02-03 23:23 UTC, multun commented on content/about/use-case/_index.en.md
> +OSRD addresses this need by providing:
```suggestion
OSRD addresses this by providing:
```

2023-03-17 13:42 UTC, axrolld requested changes
Most of my previous comments have been marked as resolved without any changes nor explainations. I'd like to discuss it because i still think some sentences are a bit strange.

2023-04-11 15:05 UTC, axrolld approved these changes

2023-04-12 16:57 UTC, axrolld approved these changes

2023-04-12 17:25 UTC, multun commented
I'm switching this PR back to draft so that it does not get merged until Christian can have a look

2023-04-13 18:39 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
Comment on typography: in French, in bulleted lists, sentences must start with a lower case letter and end with a semicolon (separated from the sentence by a non-breaking space (&nbsp;)). The last element of the list must end with a period.
When we use a ordered list, each line starts with a number (or a letter) followed by a period. In the case, each sentence should start with a capital letter and end with a semicolon (separated from the sentence by a non-breaking space (&nbsp;)). The last element of the list must end with a period.
At the end of the first sentence (new text), "planification" has only one "n".

2023-04-13 18:41 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> +Le projet a pour ambition de répondre à une large gamme de besoins autour de la plannification ferroviaire :
Planification with only one "n"

2023-04-13 18:42 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> + - [conception des plans de transport](#conception-des-plans-de-transport)
&nbsp ; ; at the end of each list item, period "." at the end of the last list item.

2023-04-13 18:44 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> +Les perspectives futures comprennent notament :
"notamment" with a double "n". To avoid the (non-)use of an article at the beginning of each sentence, the introduction sentence could be : "Les perspectives futures comprennent notamment les éléments suivants&nbsp ;:"

2023-04-13 18:45 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> + - la détection automatique de conflits[^conflit]
Remove the article "la" at the beginning of this list item.

2023-04-13 18:50 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> + - synthèse d'infrastructure macroscopique à partir d'infrastructure microscopique
The adjectives "macroscopique" and "microscopique", should possibly be explained with more details.

2023-04-13 18:52 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> +   répartition économique, qui minimise l'énergie consommée.
Why is there an ending period to this sentence? Please review all lists according to the general comment I wrote at the higher level.

2023-04-13 18:53 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> + - l’évaluation de la robustesse d'une grille horaire via un module de simulation stochastique.
End period here too!

2023-04-13 18:54 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> +commun à toutes les fonctionnalités d'OSRD, un module dédié permet de:
Missing non-breaking space before the colon "…permet de&nbsp;:".

2023-04-13 19:01 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> +(moins de 3 minutes) à ces demandes, mais aussi correctement.
This means: an automatic response must be possible…

2023-04-13 19:01 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> +Une offre de sillon correcte doit répondre à de nombreux critères, notament :
"Notamment" with a double "n".

2023-04-13 19:04 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> + - ne générer de conflits[^conflit] avec des sillons déjà établis, y compris en gare
"ne **pas** générer de conflit…" (singular form in French: there is no conflict).

2023-04-13 19:05 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> + - estimer de manière réaliste le comportement du train, et donc le moment auquel
Should rather be:
"…comportement du train et donc, le moment…" (comma moved)

2023-04-13 19:08 UTC, Christian-CROCHE commented on content/about/use-case/_index.fr.md
> +Cet outil est en cours de développement, et devrait être disponible dans
"…développement, et devrait…" the comma should be removed.

2023-04-13 19:26 UTC, Christian-CROCHE commented on content/about/use-case/_index.en.md
> + - a timetabling tool
"A time table tool" ?

2023-04-13 19:28 UTC, Christian-CROCHE commented on content/about/use-case/_index.en.md
> + - automated conflict detection[^conflict]
…and a automatic conflict resolution system?

2023-04-13 19:31 UTC, Christian-CROCHE commented on content/about/use-case/_index.en.md
> +[^conflict]: A conflicts occurs when the movement of a train interferes with another
"A conflict" without "s"

2023-04-13 19:33 UTC, Christian-CROCHE commented on content/about/use-case/_index.en.md
> +OSRD addresses this need by providing:
"…addresses these needs…"

2023-04-13 19:34 UTC, Christian-CROCHE commented on content/about/use-case/_index.en.md
> + - a timetabling tool
"time table tool"?

2023-04-13 19:36 UTC, Christian-CROCHE commented on content/about/use-case/_index.en.md
> + - automated conflict detection[^conflict]
…and resolution?

2023-04-13 19:36 UTC, Christian-CROCHE commented on content/about/use-case/_index.en.md
> + - an import tool[^railjson]
No export tool?

2023-04-14 06:41 UTC, loic-hamelin commented on content/about/use-case/_index.en.md
> + - an import tool[^railjson]
Yes of course ! But one day,  in different formats :)

2023-04-17 15:34 UTC, axrolld commented on content/about/use-case/_index.fr.md
> + - ne générer de conflits[^conflit] avec des sillons déjà établis, y compris en gare
Same here, you can use the suggestion tool 
```suggestion
 - ne pas générer de conflits[^conflit] avec des sillons déjà établis, y compris en gare
```

2023-04-17 15:36 UTC, axrolld commented on content/about/use-case/_index.en.md
> + - automated conflict detection[^conflict]
Automatic conflict resolution would be quite an ambitious project, isn't it ?

2023-04-25 13:39 UTC, multun commented on content/about/use-case/_index.fr.md
> +(moins de 3 minutes) à ces demandes, mais aussi correctement.
TODO: explicitly mention this is automated

2023-04-25 13:43 UTC, multun commented on content/about/use-case/_index.en.md
> + - a railway infrastructure database at microscopic scale
microscopic = track level

2023-04-25 14:25 UTC, multun commented on content/about/use-case/_index.en.md
> + - automated conflict detection[^conflict]
I discussed the matter with Christian, and it seems like there was a misunderstanding on what automatic conflict resolution means. OSRD will support adding a new train while avoiding creating new conflicts, but not automatically solving existing conflicts for an entire timetable. I'll try to make that clearer.

2023-07-20 15:44 UTC, celine-sncf reviewed
corrected a few spelling errors in the french version

2023-07-20 15:44 UTC, celine-sncf commented on content/about/use-case/_index.fr.md
> +schémas de dessertes[^schema-desserte]. OSRD fournit déjà un certain nombre de fonctionnés utiles à cette fin :
```suggestion
schémas de dessertes[^schema-desserte]. OSRD fournit déjà un certain nombre de fonctionnalités utiles à cette fin :
```

2023-07-20 15:44 UTC, celine-sncf commented on content/about/use-case/_index.fr.md
> + - base d'infrastructure ferroviaires à la voie
```suggestion
 - base d'infrastructure ferroviaire à la voie
```

2023-07-20 15:44 UTC, celine-sncf commented on content/about/use-case/_index.fr.md
> + - base de donnée de matériel roulant
```suggestion
 - base de données de matériel roulant
```

2023-07-20 15:44 UTC, celine-sncf commented on content/about/use-case/_index.fr.md
> +Les perspectives futures comprennent notament :
```suggestion
Les perspectives futures comprennent notamment :
```

2023-07-20 15:44 UTC, celine-sncf commented on content/about/use-case/_index.fr.md
> +Le projet a pour ambition de répondre à une large gamme de besoins autour de la plannification ferroviaire :
```suggestion
Le projet a pour ambition de répondre à une large gamme de besoins autour de la planification ferroviaire :
```

2023-07-20 15:44 UTC, celine-sncf commented on content/about/use-case/_index.fr.md
> + - fournissant une base de donnée de matériel roulant
```suggestion
 - fournissant une base de données de matériel roulant
```

2023-07-20 15:44 UTC, celine-sncf commented on content/about/use-case/_index.fr.md
> +Les pespectives futures comprennent notament :
```suggestion
Les perspectives futures comprennent notamment :
```

2023-07-20 15:44 UTC, celine-sncf commented on content/about/use-case/_index.fr.md
> + - évaluation de la robustesse d'une grille horaire via un module de simulation stochastique.
```suggestion
 - évaluation de la robustesse d'une grille horaire via un module de simulation stochastique
```

2023-07-20 15:44 UTC, celine-sncf commented on content/about/use-case/_index.fr.md
> +commun à toutes les fonctionnalités d'OSRD, un module dédié permet de:
```suggestion
commun à toutes les fonctionnalités d'OSRD, un module dédié permet de :
```

2023-07-20 15:44 UTC, celine-sncf commented on content/about/use-case/_index.fr.md
> +Une offre de sillon correcte doit répondre à de nombreux critères, notament :
```suggestion
Une offre de sillon correcte doit répondre à de nombreux critères, notamment :
```

2023-07-20 16:11 UTC, celine-sncf approved these changes
more clear now with a single page, thank you !

2023-07-21 09:01 UTC, merged

2023-07-21 13:00 UTC, El-Youssef reviewed
All comments are the same and concern the Rollingstock database.